version: '3'
services:
  api:
    container_name: api
    depends_on:
      - postgres
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - '4000:4000'
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
  postgres:
    container_name: postgres
    image: postgres:12.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db_schema.sql:/docker-entrypoint-initdb.d/init.sql