version: '3'
services:
  app:
    container_name: node_app
    depends_on:
      - prisma
      - mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
  prisma:
    container_name: prisma_server
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_SECRET}
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://${DB_ROOT}:${DB_PWD}@mongo
  mongo:
    container_name: mongodb
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~